[package]
name = "libp2p-peerstore"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
multiaddr = "0.2"
libp2p-peer = { path = "../libp2p-peer" }
