[package]
name = "multistream-select"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bytes = "0.4"
futures = { version = "0.1" }
smallvec = "0.5"
tokio-io = "0.1"

[dev-dependencies]
tokio-core = "0.1"
